spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beauty?characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "123456"
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.pengling.beauty.mapper
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8081